import assert from "node:assert/strict";
import test from "node:test";

import { PartnerApiError } from "../src/lib/partner-platform/errors.ts";
import { getRequiredPartnerIndexNames } from "../src/lib/partner-platform/indexes.ts";
import { buildPartnerPilotReport } from "../src/lib/partner-platform/pilot.ts";
import { evaluatePartnerPilotMetrics,getPartnerPilotMonitoringSnapshot } from "../src/lib/partner-platform/pilot-monitoring.ts";
import { superAdminIntegrationActionSchema } from "../src/lib/partner-platform/phase8-schemas.ts";
import { executeSuperAdminIntegrationAction,getSuperAdminIntegrationConsole } from "../src/lib/partner-platform/super-admin-console.ts";
import { InMemoryMongoDatabase } from "./support/in-memory-mongo.mjs";

const now=new Date("2026-08-06T12:00:00.000Z");
const pepper="phase-11-test-pepper-with-at-least-thirty-two-characters";
const owner={kind:"internal",userId:"phase11-owner",role:"super_admin"};
const pilotData={agreedWorkflows:["shipment_creation","multiple_file_upload","shipment_tracking","invoice_download","payment_proof","webhook_delivery"],expectedVolume:{requestsPerDay:500,shipmentsPerDay:20,uploadBytesPerDay:50*1024*1024},pilotQuota:{requestsPerMinute:60,shipmentsPerDay:100,uploadBytesPerDay:500*1024*1024},supportContactEmail:"pilot-support@partner.example"};
async function execute(db,action,at=now){return executeSuperAdminIntegrationAction({db,principal:owner,action,pepper,now:at});}
async function setup(suffix="pilot"){const db=new InMemoryMongoDatabase(`phase11-${suffix}`);const org=(await execute(db,{action:"organization.create",data:{name:`Phase 11 ${suffix}`,slug:`phase-11-${suffix}`}})).organization;await execute(db,{action:"organization.update",organizationId:org.id,data:{status:"active"}});const app=(await execute(db,{action:"application.create",organizationId:org.id,data:{name:"Pilot app",environmentAccess:["test","live"],scopes:["shipments:create","shipments:read","documents:write","webhooks:manage"]}})).application;return{db,org,app};}
async function denied(promise,code,status=409){await assert.rejects(promise,error=>error instanceof PartnerApiError&&error.code===code&&error.status===status);}
async function approve(context){await execute(context.db,{action:"pilot.configure",organizationId:context.org.id,data:pilotData});await execute(context.db,{action:"pilot.security_review",organizationId:context.org.id,data:{decision:"approved",keyStorageApproach:"managed_secret_store",rotationOwner:"Partner security owner",notes:"No credentials in source control"}});await execute(context.db,{action:"pilot.sandbox_decision",organizationId:context.org.id,accepted:true,notes:"Sandbox workflow accepted"});return execute(context.db,{action:"pilot.live_decision",organizationId:context.org.id,approved:true,notes:"Owner approved limited live pilot"});}

test("pilot configuration applies conservative quotas and exposes only safe console fields",async()=>{const c=await setup("configuration");const configured=await execute(c.db,{action:"pilot.configure",organizationId:c.org.id,data:pilotData});assert.equal(configured.pilot.status,"sandbox");const storedOrg=await c.db.collection("organizations").findOne({publicId:c.org.id});assert.deepEqual(storedOrg.limits,pilotData.pilotQuota);const consoleData=await getSuperAdminIntegrationConsole({db:c.db,principal:owner});assert.equal(consoleData.pilots[0].organizationId,c.org.id);const serialized=JSON.stringify(consoleData.pilots);assert.equal(serialized.includes(storedOrg._id.toString()),false);assert.equal(serialized.includes("reviewedBy"),false);assert.equal(serialized.includes("createdBy"),false);});

test("live credentials remain blocked until approval and are revoked when approval is withdrawn",async()=>{const c=await setup("gates");await denied(execute(c.db,{action:"credential.issue",organizationId:c.org.id,applicationId:c.app.id,environment:"live",scopes:["shipments:read"]}),"pilot_not_ready");await execute(c.db,{action:"pilot.configure",organizationId:c.org.id,data:pilotData});await execute(c.db,{action:"pilot.sandbox_decision",organizationId:c.org.id,accepted:true});await denied(execute(c.db,{action:"pilot.live_decision",organizationId:c.org.id,approved:true}),"pilot_not_ready");await execute(c.db,{action:"pilot.security_review",organizationId:c.org.id,data:{decision:"approved",keyStorageApproach:"encrypted_server_environment",rotationOwner:"Technical lead"}});await execute(c.db,{action:"pilot.live_decision",organizationId:c.org.id,approved:true});await denied(execute(c.db,{action:"pilot.start",organizationId:c.org.id}),"pilot_not_ready");const first=await execute(c.db,{action:"credential.issue",organizationId:c.org.id,applicationId:c.app.id,environment:"live",scopes:["shipments:read"]});assert.match(first.apiKey,/^csl_live_/);await execute(c.db,{action:"pilot.live_decision",organizationId:c.org.id,approved:false});assert.equal((await c.db.collection("api_credentials").findOne({publicId:first.credential.publicId})).status,"revoked");await denied(execute(c.db,{action:"credential.issue",organizationId:c.org.id,applicationId:c.app.id,environment:"live",scopes:["shipments:read"]}),"pilot_not_ready");await execute(c.db,{action:"pilot.live_decision",organizationId:c.org.id,approved:true});const replacement=await execute(c.db,{action:"credential.issue",organizationId:c.org.id,applicationId:c.app.id,environment:"live",scopes:["shipments:read"]});assert.match(replacement.apiKey,/^csl_live_/);const started=await execute(c.db,{action:"pilot.start",organizationId:c.org.id});assert.equal(started.pilot.status,"live");});

test("daily pilot metrics, feedback resolution and completion enforce the agreed exit criteria",async()=>{const c=await setup("completion");await approve(c);await execute(c.db,{action:"credential.issue",organizationId:c.org.id,applicationId:c.app.id,environment:"live",scopes:["shipments:read"]});await execute(c.db,{action:"pilot.start",organizationId:c.org.id});const organization=await c.db.collection("organizations").findOne({publicId:c.org.id});const application=await c.db.collection("api_clients").findOne({publicId:c.app.id});await c.db.collection("api_request_logs").insertMany(Array.from({length:100},(_,i)=>({organizationId:organization._id,environment:"live",responseStatus:i===99?500:200,durationMs:i+1,createdAt:now})));await c.db.collection("shipments").insertOne({organizationId:organization._id,apiClientId:application._id,environment:"live",createdAt:now});await c.db.collection("upload_intents").insertMany([{organizationId:organization._id,declaredSize:100,createdAt:now},{organizationId:organization._id,declaredSize:200,createdAt:now}]);await c.db.collection("webhook_deliveries").insertOne({organizationId:organization._id,environment:"live",status:"succeeded",createdAt:now});const observation=(await execute(c.db,{action:"pilot.observation_create",organizationId:c.org.id,data:{kind:"defect",category:"documentation",severity:"high",summary:"Quick-start wording unclear"}})).observation;await execute(c.db,{action:"pilot.acceptance_update",organizationId:c.org.id,data:{productionWorkflowsCompleted:true,supportProcessAccepted:true,noIncidentsConfirmed:true}});await denied(execute(c.db,{action:"pilot.complete",organizationId:c.org.id}),"pilot_not_ready");await execute(c.db,{action:"pilot.observation_resolve",organizationId:c.org.id,observationId:observation.id,resolution:"Quick-start clarified and partner confirmed"});const completed=await execute(c.db,{action:"pilot.complete",organizationId:c.org.id});assert.equal(completed.pilot.status,"completed");assert.equal(completed.pilot.metrics.requests,100);assert.equal(completed.pilot.metrics.p95LatencyMs,95);assert.equal(completed.pilot.metrics.webhookReliabilityPercent,100);assert.equal(completed.pilot.metrics.uploadBytes,300);assert.deepEqual(completed.pilot.blockers,[]);});

test("prohibited incidents permanently block completion and observations stay tenant isolated",async()=>{const a=await setup("incident-a"),b=await setup("incident-b");await approve(a);await execute(a.db,{action:"credential.issue",organizationId:a.org.id,applicationId:a.app.id,environment:"live",scopes:["shipments:read"]});await execute(a.db,{action:"pilot.start",organizationId:a.org.id});await execute(a.db,{action:"pilot.acceptance_update",organizationId:a.org.id,data:{productionWorkflowsCompleted:true,supportProcessAccepted:true,noIncidentsConfirmed:true}});const fakeKey=["csl_live_abcdefghijklmnop","A".repeat(43)].join(".");const incident=(await execute(a.db,{action:"pilot.observation_create",organizationId:a.org.id,data:{kind:"incident",category:"private_file",severity:"critical",summary:"Private-file isolation investigation",details:`Accidental value ${fakeKey}`}})).observation;assert.equal(incident.details.includes(fakeKey),false);await execute(a.db,{action:"pilot.observation_resolve",organizationId:a.org.id,observationId:incident.id,resolution:"Contained"});await denied(execute(a.db,{action:"pilot.complete",organizationId:a.org.id}),"pilot_not_ready");await execute(b.db,{action:"pilot.configure",organizationId:b.org.id,data:pilotData});await denied(execute(a.db,{action:"pilot.observation_resolve",organizationId:b.org.id,observationId:incident.id,resolution:"Invalid cross-tenant action"}),"resource_not_found",404);const pilot=await a.db.collection("partner_pilots").findOne({organizationId:(await a.db.collection("organizations").findOne({publicId:a.org.id}))._id});const report=await buildPartnerPilotReport({db:a.db,pilot,now});assert.equal(report.readyToComplete,false);assert.ok(report.blockers.some(item=>item.includes("prohibited")));});

test("Phase 11 action schemas and indexes cover pilot governance without secret fields",()=>{assert.equal(superAdminIntegrationActionSchema.safeParse({action:"pilot.configure",organizationId:"org_abcdefghijklmnop",data:pilotData}).success,true);assert.equal(superAdminIntegrationActionSchema.safeParse({action:"pilot.security_review",organizationId:"org_abcdefghijklmnop",data:{decision:"approved",keyStorageApproach:"plaintext_file",rotationOwner:"Owner",apiKey:"secret"}}).success,false);assert.equal(superAdminIntegrationActionSchema.safeParse({action:"pilot.observation_create",organizationId:"org_abcdefghijklmnop",data:{kind:"defect",category:"tenant_isolation",severity:"critical",summary:"Wrong classification"}}).success,false);const names=new Set(getRequiredPartnerIndexNames());for(const name of ["partner_pilots_public_id_unique","partner_pilots_organization_unique","partner_pilot_observations_public_id_unique","partner_pilot_observations_org_status_created"])assert.ok(names.has(name),name);});
test("daily pilot monitoring raises stable threshold alerts without internal organization IDs",async()=>{const alerts=evaluatePartnerPilotMetrics({requests:100,serverErrors:5,errorRatePercent:5,p95LatencyMs:1500,webhookDeliveries:10,webhookReliabilityPercent:90,openHighSeverity:1});assert.deepEqual(alerts.map(item=>item.code),["pilot_api_error_rate","pilot_api_latency","pilot_webhook_reliability","pilot_open_severity"]);const c=await setup("monitoring");await execute(c.db,{action:"pilot.configure",organizationId:c.org.id,data:pilotData});const snapshot=await getPartnerPilotMonitoringSnapshot(c.db,now);assert.equal(snapshot.activePilots,1);assert.equal(snapshot.pilots[0].organizationId,c.org.id);assert.equal(JSON.stringify(snapshot).includes((await c.db.collection("organizations").findOne({publicId:c.org.id}))._id.toString()),false);});
