import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import { createOrganization } from "../src/lib/partner-platform/repositories.ts";
import { ensurePartnerCoreIndexes } from "../src/lib/partner-platform/core-indexes.ts";
import { PartnerApiError } from "../src/lib/partner-platform/errors.ts";
import { authenticatePartnerPortalCredentials, createPartnerPortalUser, resolvePartnerPortalSession } from "../src/lib/partner-platform/portal-auth.ts";
import { executePartnerPortalAction, getPartnerPortalConsole } from "../src/lib/partner-platform/portal-console.ts";
import { createPartnerPortalSessionToken, verifyPartnerPortalSessionToken } from "../src/lib/partner-platform/portal-session.ts";
import { partnerPortalActionSchema, partnerPortalLoginSchema } from "../src/lib/partner-platform/phase9-schemas.ts";
import { InMemoryMongoDatabase } from "./support/in-memory-mongo.mjs";

const now = new Date("2026-08-06T12:00:00.000Z");
const secret = "phase-nine-session-secret-with-more-than-thirty-two-characters";
const pepper = "phase-nine-api-pepper-with-more-than-thirty-two-characters";
async function setup(suffix="owner", role="owner") { const db=new InMemoryMongoDatabase(`phase9_${suffix}`); await ensurePartnerCoreIndexes(db); const organization=await createOrganization(db,{name:`Phase 9 ${suffix}`,slug:`phase-9-${suffix}`,status:"active"},now); const user=await createPartnerPortalUser({db,organizationId:organization._id,name:`${suffix} user`,email:`${suffix}@example.com`,role,password:"Temporary-Password-123!",now}); const principal={kind:"partner_portal",userId:user._id.toString(),userPublicId:user.publicId,organizationId:organization._id.toString(),organizationPublicId:organization.publicId,role,name:user.name,email:user.email,mustChangePassword:true}; return {db,organization,user,principal}; }
async function denied(promise, code="resource_not_found", status=404){await assert.rejects(promise,(error)=>error instanceof PartnerApiError&&error.code===code&&error.status===status)}

test("portal sessions are signed, expire, reject tampering, and resolve active membership",async()=>{const c=await setup("session");const token=createPartnerPortalSessionToken({userId:c.user._id.toString(),organizationId:c.organization._id.toString(),secret,now});assert.ok(verifyPartnerPortalSessionToken({token,secret,now}));assert.equal(verifyPartnerPortalSessionToken({token:`${token}x`,secret,now}),null);assert.equal(verifyPartnerPortalSessionToken({token,secret,now:new Date(now.getTime()+13*60*60*1000)}),null);const resolved=await resolvePartnerPortalSession({db:c.db,token,secret,now});assert.equal(resolved.organizationPublicId,c.organization.publicId);});
test("organization slug plus email authenticates only the matching active membership",async()=>{const c=await setup("login");const principal=await authenticatePartnerPortalCredentials({db:c.db,organizationSlug:c.organization.slug,email:c.user.email,password:"Temporary-Password-123!"});assert.equal(principal.userPublicId,c.user.publicId);await denied(authenticatePartnerPortalCredentials({db:c.db,organizationSlug:"wrong-org",email:c.user.email,password:"Temporary-Password-123!"}),"authentication_required",401);});
test("portal roles deny privileged changes while owner creates sandbox-only applications",async()=>{const owner=await setup("roles");const created=await executePartnerPortalAction({db:owner.db,principal:owner.principal,action:{action:"application.create",data:{name:"Sandbox app",scopes:["shipments:create","shipments:read"]}},pepper,now});assert.deepEqual(created.application.environmentAccess,["test"]);const viewer={...owner.principal,role:"read_only"};await denied(executePartnerPortalAction({db:owner.db,principal:viewer,action:{action:"application.create",data:{name:"Denied app",scopes:["shipments:read"]}},pepper,now}));});
test("portal keys are revealed once, constrained to approved access, and absent from console reads",async()=>{const c=await setup("keys");const created=await executePartnerPortalAction({db:c.db,principal:c.principal,action:{action:"application.create",data:{name:"Key app",scopes:["shipments:read"]}},pepper,now});await denied(executePartnerPortalAction({db:c.db,principal:c.principal,action:{action:"credential.issue",applicationId:created.application.id,environment:"live",scopes:["shipments:read"]},pepper,now}),"validation_failed",422);const issued=await executePartnerPortalAction({db:c.db,principal:c.principal,action:{action:"credential.issue",applicationId:created.application.id,environment:"test",scopes:["shipments:read"]},pepper,now});assert.match(issued.apiKey,/^csl_test_/);const consoleData=await getPartnerPortalConsole({db:c.db,principal:c.principal,environment:"test"});assert.equal(JSON.stringify(consoleData).includes(issued.apiKey),false);assert.equal(JSON.stringify(consoleData).includes("secretHash"),false);});
test("portal console data is isolated by organization and environment",async()=>{const a=await setup("tenant-a");const b=await setup("tenant-b");await a.db.collection("shipments").insertOne({organizationId:a.organization._id,environment:"test",publicId:"shp_abcdefghijklmnop",trackingId:"CLL-A",receiverName:"A",status:"pending",createdAt:now,updatedAt:now});await a.db.collection("shipments").insertOne({organizationId:b.organization._id,environment:"test",publicId:"shp_qrstuvwxyzabcdef",trackingId:"CLL-B",receiverName:"B",status:"pending",createdAt:now,updatedAt:now});const data=await getPartnerPortalConsole({db:a.db,principal:a.principal,environment:"test"});assert.deepEqual(data.shipments.map(item=>item.trackingId),["CLL-A"]);});
test("Phase 9 schemas and downloadable API artifacts form a usable test-mode contract",async()=>{assert.equal(partnerPortalLoginSchema.safeParse({organizationSlug:"acme-logistics",email:"dev@acme.test",password:"password"}).success,true);assert.equal(partnerPortalActionSchema.safeParse({action:"credential.issue",applicationId:"app_abcdefghijklmnop",environment:"live",scopes:["root:all"]}).success,false);const openapi=JSON.parse(await readFile(new URL("../public/openapi/cascade-partner-v1.json",import.meta.url),"utf8"));const collection=JSON.parse(await readFile(new URL("../public/collections/cascade-partner-v1.postman.json",import.meta.url),"utf8"));for(const path of ["/me","/uploads","/shipments","/webhook-endpoints","/webhook-deliveries"])assert.ok(openapi.paths[path],path);assert.match(collection.variable.find(item=>item.key==="apiKey").value,/csl_test_/);});
